### ISSUE TITLE
Chapter 24 services

### ISSUE THREAD

**Issue by gungmas** [PacktPublishing/React-and-React-Native-Second-Edition#5]
I try to run services locally by executing:
npm install

and then to start the service:
node index.js 

but I get the following error that I don't understand:

/Users/mikael/Desktop/React-and-React-Native-Second-Edition-master/_rnserver/index.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

I moved the files to a new directory (_rnserver) before my attempt.

What might be the problem?

**Comment by adamboduch** [comment]
Hi @gungmas. I'm sorry it took me so long to get to this - not sure how I missed it.

If you pull the latest from this repo, and run `npm start` to start the services.
